/* Automatically @generated by tree-sitter v0.25.9 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 34
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 32
#define ALIAS_COUNT 1
#define TOKEN_COUNT 20
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_ATstartuml = 2,
  anon_sym_ATenduml = 3,
  anon_sym_BANG = 4,
  anon_sym_include = 5,
  anon_sym_SPACE = 6,
  anon_sym_LBRACE = 7,
  anon_sym_RBRACE = 8,
  anon_sym_LBRACK = 9,
  aux_sym_link_token1 = 10,
  anon_sym_RBRACK = 11,
  anon_sym_LPAREN = 12,
  anon_sym_COMMA = 13,
  anon_sym_RPAREN = 14,
  anon_sym_EQ = 15,
  sym_string = 16,
  sym_single_quote_string = 17,
  sym_comment = 18,
  sym_unqouted_string = 19,
  sym_diagram = 20,
  sym__startend = 21,
  sym_preprocessor = 22,
  sym_procedure = 23,
  sym_block = 24,
  sym_link = 25,
  sym_argument_list = 26,
  sym__expression = 27,
  sym_named_parameter = 28,
  aux_sym_diagram_repeat1 = 29,
  aux_sym_block_repeat1 = 30,
  aux_sym_argument_list_repeat1 = 31,
  alias_sym_procedure_identifier = 32,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_ATstartuml] = "@startuml",
  [anon_sym_ATenduml] = "@enduml",
  [anon_sym_BANG] = "!",
  [anon_sym_include] = "include",
  [anon_sym_SPACE] = " ",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACK] = "[",
  [aux_sym_link_token1] = "link_token1",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_EQ] = "=",
  [sym_string] = "string",
  [sym_single_quote_string] = "single_quote_string",
  [sym_comment] = "comment",
  [sym_unqouted_string] = "unqouted_string",
  [sym_diagram] = "diagram",
  [sym__startend] = "_startend",
  [sym_preprocessor] = "preprocessor",
  [sym_procedure] = "procedure",
  [sym_block] = "block",
  [sym_link] = "link",
  [sym_argument_list] = "argument_list",
  [sym__expression] = "_expression",
  [sym_named_parameter] = "named_parameter",
  [aux_sym_diagram_repeat1] = "diagram_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_argument_list_repeat1] = "argument_list_repeat1",
  [alias_sym_procedure_identifier] = "procedure_identifier",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_ATstartuml] = anon_sym_ATstartuml,
  [anon_sym_ATenduml] = anon_sym_ATenduml,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_include] = anon_sym_include,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [aux_sym_link_token1] = aux_sym_link_token1,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_string] = sym_string,
  [sym_single_quote_string] = sym_single_quote_string,
  [sym_comment] = sym_comment,
  [sym_unqouted_string] = sym_unqouted_string,
  [sym_diagram] = sym_diagram,
  [sym__startend] = sym__startend,
  [sym_preprocessor] = sym_preprocessor,
  [sym_procedure] = sym_procedure,
  [sym_block] = sym_block,
  [sym_link] = sym_link,
  [sym_argument_list] = sym_argument_list,
  [sym__expression] = sym__expression,
  [sym_named_parameter] = sym_named_parameter,
  [aux_sym_diagram_repeat1] = aux_sym_diagram_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_argument_list_repeat1] = aux_sym_argument_list_repeat1,
  [alias_sym_procedure_identifier] = alias_sym_procedure_identifier,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_ATstartuml] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATenduml] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_include] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_link_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_single_quote_string] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_unqouted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_diagram] = {
    .visible = true,
    .named = true,
  },
  [sym__startend] = {
    .visible = false,
    .named = true,
  },
  [sym_preprocessor] = {
    .visible = true,
    .named = true,
  },
  [sym_procedure] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_link] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_named_parameter] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_diagram_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_procedure_identifier] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_url = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_url] = "url",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [2] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_url, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = alias_sym_procedure_identifier,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(25);
      ADVANCE_MAP(
        '!', 28,
        '"', 7,
        '$', 22,
        '\'', 44,
        '(', 36,
        ')', 38,
        ',', 37,
        '=', 39,
        '@', 11,
        '[', 32,
        ']', 35,
        '{', 30,
        '}', 31,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(1);
      if (lookahead == ',' ||
          lookahead == '[') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(3);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(46);
      if (lookahead == '[') ADVANCE(2);
      if (lookahead == '$' ||
          lookahead == ']') ADVANCE(48);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == ',') ADVANCE(46);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(47);
      if (lookahead == ',') ADVANCE(46);
      if (lookahead == '[') ADVANCE(2);
      if (lookahead == '$' ||
          lookahead == ']') ADVANCE(48);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(47);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(49);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '$' ||
          lookahead == ',' ||
          lookahead == ']') ADVANCE(48);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(29);
      if (lookahead == '"') ADVANCE(7);
      if (lookahead == '$') ADVANCE(22);
      if (lookahead == '\'') ADVANCE(8);
      if (lookahead == ')') ADVANCE(38);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(5);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(7);
      if (lookahead == '$') ADVANCE(22);
      if (lookahead == '\'') ADVANCE(8);
      if (lookahead == ')') ADVANCE(38);
      if (lookahead == ',') ADVANCE(37);
      if (lookahead == '=') ADVANCE(39);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 7:
      if (lookahead == '"') ADVANCE(41);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '\'') ADVANCE(42);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(17);
      END_STATE();
    case 10:
      if (lookahead == 'd') ADVANCE(20);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(16);
      if (lookahead == 's') ADVANCE(18);
      END_STATE();
    case 12:
      if (lookahead == 'l') ADVANCE(27);
      END_STATE();
    case 13:
      if (lookahead == 'l') ADVANCE(26);
      END_STATE();
    case 14:
      if (lookahead == 'm') ADVANCE(12);
      END_STATE();
    case 15:
      if (lookahead == 'm') ADVANCE(13);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(10);
      END_STATE();
    case 17:
      if (lookahead == 'r') ADVANCE(19);
      END_STATE();
    case 18:
      if (lookahead == 't') ADVANCE(9);
      END_STATE();
    case 19:
      if (lookahead == 't') ADVANCE(21);
      END_STATE();
    case 20:
      if (lookahead == 'u') ADVANCE(14);
      END_STATE();
    case 21:
      if (lookahead == 'u') ADVANCE(15);
      END_STATE();
    case 22:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 23:
      if (eof) ADVANCE(25);
      ADVANCE_MAP(
        ' ', 29,
        '!', 28,
        '$', 22,
        '\'', 45,
        '@', 11,
        '[', 32,
        '{', 30,
        '}', 31,
      );
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 24:
      if (eof) ADVANCE(25);
      if (lookahead == '!') ADVANCE(28);
      if (lookahead == '$') ADVANCE(22);
      if (lookahead == '\'') ADVANCE(45);
      if (lookahead == '@') ADVANCE(11);
      if (lookahead == '[') ADVANCE(32);
      if (lookahead == '{') ADVANCE(30);
      if (lookahead == '}') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(24);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_ATstartuml);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_ATenduml);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == ' ') ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_link_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(34);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_link_token1);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '_') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_single_quote_string);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_single_quote_string);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(45);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\'') ADVANCE(43);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(8);
      if (lookahead != 0) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_unqouted_string);
      if (lookahead == '\n') ADVANCE(46);
      if (lookahead == '[') ADVANCE(2);
      if (lookahead == '$' ||
          lookahead == ']') ADVANCE(48);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == ',') ADVANCE(46);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_unqouted_string);
      if (lookahead == '\n') ADVANCE(47);
      if (lookahead == ',') ADVANCE(46);
      if (lookahead == '[') ADVANCE(2);
      if (lookahead == '$' ||
          lookahead == ']') ADVANCE(48);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(47);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_unqouted_string);
      if (lookahead == '\n') ADVANCE(49);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '$' ||
          lookahead == ',' ||
          lookahead == ']') ADVANCE(48);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_unqouted_string);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '$' ||
          lookahead == ',' ||
          lookahead == ']') ADVANCE(49);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'i') ADVANCE(1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'n') ADVANCE(2);
      END_STATE();
    case 2:
      if (lookahead == 'c') ADVANCE(3);
      END_STATE();
    case 3:
      if (lookahead == 'l') ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == 'u') ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == 'd') ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(7);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_include);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 24},
  [2] = {.lex_state = 23},
  [3] = {.lex_state = 24},
  [4] = {.lex_state = 24},
  [5] = {.lex_state = 24},
  [6] = {.lex_state = 23},
  [7] = {.lex_state = 6},
  [8] = {.lex_state = 24},
  [9] = {.lex_state = 6},
  [10] = {.lex_state = 24},
  [11] = {.lex_state = 24},
  [12] = {.lex_state = 24},
  [13] = {.lex_state = 24},
  [14] = {.lex_state = 6},
  [15] = {.lex_state = 6},
  [16] = {.lex_state = 24},
  [17] = {.lex_state = 6},
  [18] = {.lex_state = 6},
  [19] = {.lex_state = 5},
  [20] = {.lex_state = 6},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 33},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 23},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_ATstartuml] = ACTIONS(1),
    [anon_sym_ATenduml] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_include] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_single_quote_string] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_diagram] = STATE(33),
    [sym__startend] = STATE(4),
    [sym_preprocessor] = STATE(4),
    [sym_procedure] = STATE(4),
    [aux_sym_diagram_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_identifier] = ACTIONS(5),
    [anon_sym_ATstartuml] = ACTIONS(7),
    [anon_sym_ATenduml] = ACTIONS(7),
    [anon_sym_BANG] = ACTIONS(9),
    [sym_comment] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      anon_sym_SPACE,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    STATE(8), 2,
      sym_block,
      sym_link,
    ACTIONS(13), 6,
      anon_sym_ATstartuml,
      anon_sym_ATenduml,
      anon_sym_BANG,
      anon_sym_RBRACE,
      sym_identifier,
      sym_comment,
  [25] = 4,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    STATE(11), 2,
      sym_block,
      sym_link,
    ACTIONS(21), 7,
      ts_builtin_sym_end,
      anon_sym_ATstartuml,
      anon_sym_ATenduml,
      anon_sym_BANG,
      anon_sym_RBRACE,
      sym_identifier,
      sym_comment,
  [45] = 5,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_BANG,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(29), 3,
      anon_sym_ATstartuml,
      anon_sym_ATenduml,
      sym_comment,
    STATE(5), 4,
      sym__startend,
      sym_preprocessor,
      sym_procedure,
      aux_sym_diagram_repeat1,
  [66] = 5,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(39), 1,
      anon_sym_BANG,
    ACTIONS(36), 3,
      anon_sym_ATstartuml,
      anon_sym_ATenduml,
      sym_comment,
    STATE(5), 4,
      sym__startend,
      sym_preprocessor,
      sym_procedure,
      aux_sym_diagram_repeat1,
  [87] = 2,
    ACTIONS(42), 2,
      ts_builtin_sym_end,
      anon_sym_SPACE,
    ACTIONS(44), 8,
      anon_sym_ATstartuml,
      anon_sym_ATenduml,
      anon_sym_BANG,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_comment,
  [102] = 5,
    ACTIONS(46), 1,
      sym_identifier,
    ACTIONS(48), 1,
      anon_sym_RPAREN,
    STATE(9), 1,
      aux_sym_argument_list_repeat1,
    ACTIONS(50), 2,
      sym_string,
      sym_single_quote_string,
    STATE(17), 2,
      sym__expression,
      sym_named_parameter,
  [120] = 1,
    ACTIONS(21), 7,
      ts_builtin_sym_end,
      anon_sym_ATstartuml,
      anon_sym_ATenduml,
      anon_sym_BANG,
      anon_sym_RBRACE,
      sym_identifier,
      sym_comment,
  [130] = 5,
    ACTIONS(52), 1,
      sym_identifier,
    ACTIONS(55), 1,
      anon_sym_RPAREN,
    STATE(9), 1,
      aux_sym_argument_list_repeat1,
    ACTIONS(57), 2,
      sym_string,
      sym_single_quote_string,
    STATE(17), 2,
      sym__expression,
      sym_named_parameter,
  [148] = 1,
    ACTIONS(60), 7,
      ts_builtin_sym_end,
      anon_sym_ATstartuml,
      anon_sym_ATenduml,
      anon_sym_BANG,
      anon_sym_RBRACE,
      sym_identifier,
      sym_comment,
  [158] = 1,
    ACTIONS(62), 7,
      ts_builtin_sym_end,
      anon_sym_ATstartuml,
      anon_sym_ATenduml,
      anon_sym_BANG,
      anon_sym_RBRACE,
      sym_identifier,
      sym_comment,
  [168] = 1,
    ACTIONS(64), 7,
      ts_builtin_sym_end,
      anon_sym_ATstartuml,
      anon_sym_ATenduml,
      anon_sym_BANG,
      anon_sym_RBRACE,
      sym_identifier,
      sym_comment,
  [178] = 1,
    ACTIONS(66), 7,
      ts_builtin_sym_end,
      anon_sym_ATstartuml,
      anon_sym_ATenduml,
      anon_sym_BANG,
      anon_sym_RBRACE,
      sym_identifier,
      sym_comment,
  [188] = 4,
    ACTIONS(46), 1,
      sym_identifier,
    STATE(7), 1,
      aux_sym_argument_list_repeat1,
    ACTIONS(50), 2,
      sym_string,
      sym_single_quote_string,
    STATE(17), 2,
      sym__expression,
      sym_named_parameter,
  [203] = 2,
    ACTIONS(70), 1,
      anon_sym_EQ,
    ACTIONS(68), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_identifier,
      sym_string,
      sym_single_quote_string,
  [214] = 1,
    ACTIONS(72), 6,
      ts_builtin_sym_end,
      anon_sym_ATstartuml,
      anon_sym_ATenduml,
      anon_sym_BANG,
      sym_identifier,
      sym_comment,
  [223] = 2,
    ACTIONS(76), 1,
      anon_sym_COMMA,
    ACTIONS(74), 4,
      anon_sym_RPAREN,
      sym_identifier,
      sym_string,
      sym_single_quote_string,
  [233] = 1,
    ACTIONS(78), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_identifier,
      sym_string,
      sym_single_quote_string,
  [241] = 2,
    ACTIONS(82), 1,
      anon_sym_SPACE,
    ACTIONS(80), 4,
      anon_sym_RPAREN,
      sym_identifier,
      sym_string,
      sym_single_quote_string,
  [251] = 1,
    ACTIONS(84), 4,
      anon_sym_RPAREN,
      sym_identifier,
      sym_string,
      sym_single_quote_string,
  [258] = 3,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(86), 1,
      anon_sym_RBRACE,
    STATE(23), 2,
      sym_procedure,
      aux_sym_block_repeat1,
  [269] = 3,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(88), 1,
      anon_sym_RBRACE,
    STATE(21), 2,
      sym_procedure,
      aux_sym_block_repeat1,
  [280] = 3,
    ACTIONS(90), 1,
      sym_identifier,
    ACTIONS(93), 1,
      anon_sym_RBRACE,
    STATE(23), 2,
      sym_procedure,
      aux_sym_block_repeat1,
  [291] = 1,
    ACTIONS(95), 2,
      anon_sym_include,
      sym_identifier,
  [296] = 2,
    ACTIONS(97), 1,
      anon_sym_LPAREN,
    STATE(2), 1,
      sym_argument_list,
  [303] = 1,
    ACTIONS(99), 1,
      anon_sym_LBRACK,
  [307] = 1,
    ACTIONS(101), 1,
      sym_unqouted_string,
  [311] = 1,
    ACTIONS(103), 1,
      aux_sym_link_token1,
  [315] = 1,
    ACTIONS(105), 1,
      sym_string,
  [319] = 1,
    ACTIONS(107), 1,
      anon_sym_SPACE,
  [323] = 1,
    ACTIONS(109), 1,
      anon_sym_RBRACK,
  [327] = 1,
    ACTIONS(111), 1,
      anon_sym_RBRACK,
  [331] = 1,
    ACTIONS(113), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 25,
  [SMALL_STATE(4)] = 45,
  [SMALL_STATE(5)] = 66,
  [SMALL_STATE(6)] = 87,
  [SMALL_STATE(7)] = 102,
  [SMALL_STATE(8)] = 120,
  [SMALL_STATE(9)] = 130,
  [SMALL_STATE(10)] = 148,
  [SMALL_STATE(11)] = 158,
  [SMALL_STATE(12)] = 168,
  [SMALL_STATE(13)] = 178,
  [SMALL_STATE(14)] = 188,
  [SMALL_STATE(15)] = 203,
  [SMALL_STATE(16)] = 214,
  [SMALL_STATE(17)] = 223,
  [SMALL_STATE(18)] = 233,
  [SMALL_STATE(19)] = 241,
  [SMALL_STATE(20)] = 251,
  [SMALL_STATE(21)] = 258,
  [SMALL_STATE(22)] = 269,
  [SMALL_STATE(23)] = 280,
  [SMALL_STATE(24)] = 291,
  [SMALL_STATE(25)] = 296,
  [SMALL_STATE(26)] = 303,
  [SMALL_STATE(27)] = 307,
  [SMALL_STATE(28)] = 311,
  [SMALL_STATE(29)] = 315,
  [SMALL_STATE(30)] = 319,
  [SMALL_STATE(31)] = 323,
  [SMALL_STATE(32)] = 327,
  [SMALL_STATE(33)] = 331,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_diagram, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_procedure, 2, 0, 1),
  [13] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_procedure, 2, 0, 1),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_procedure, 3, 0, 1),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_diagram, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_diagram_repeat1, 2, 0, 0),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_diagram_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_diagram_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_diagram_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 3, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 3, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_procedure, 4, 0, 1),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link, 5, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preprocessor, 4, 0, 2),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_parameter, 3, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 3, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [113] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_plantuml(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
